apiVersion: v1
kind: Template
metadata:
  name: advise-reporter-consumer
  annotations:
    description: "Thoth: Advise Reporter Consumer"
    openshift.io/display-name: "Thoth Core: Advise Reporter Consumer"
    version: 0.6.0-dev
    tags: thoth,advise-reporter-consumer,ai-stacks,aistacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to deploy Thoth
      Advise Reporter Consumer on OpenShift.
    template.openshift.io/provider-display-name: "Red Hat, Inc."
  labels:
    template: advise-reporter-consumer
    app: thoth
    component: advise-reporter-consumer

parameters:
  - description: "Project the ImageStream to be use lives in."
    displayName: "ImageStream Project"
    required: true
    name: IMAGE_STREAM_NAMESPACE

  - description: "Tag of the ImageStream to be use."
    displayName: "ImageStream Tag"
    required: true
    name: IMAGE_STREAM_TAG
    value: "latest"

  - description: "Subcommand to run in the package-update-job repository."
    displayName: "Subcommand"
    required: true
    name: "SUBCOMMAND"
    value: "consumer"

  - description: "Thoth environment (test, stage, prod)."
    displayName: "Environment"
    required: true
    name: "THOTH_ENVIRONMENT"

objects:
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: advise-reporter-consumer
      annotations:
        thoth-station.ninja/template-version: 0.1.0
      labels:
        app: thoth
        component: advise-reporter-consumer
    spec:
      to:
        kind: Service
        name: advise-reporter-consumer

  - kind: Service
    apiVersion: v1
    metadata:
      annotations:
        thoth-station.ninja/template-version: 0.1.0
      labels:
        app: thoth
        component: advise-reporter-consumer
      name: advise-reporter-consumer
    spec:
      ports:
        - port: 80
          protocol: TCP
          targetPort: 8080
      selector:
        service: advise-reporter-consumer

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      annotations:
        thoth-station.ninja/template-version: 0.1.0
      labels:
        app: thoth
        component: advise-reporter-consumer
      name: advise-reporter-consumer
    spec:
      replicas: 1
      selector:
        service: advise-reporter-consumer
      template:
        metadata:
          labels:
            service: advise-reporter-consumer
        spec:
          containers:
            - name: advise-reporter-consumer
              imagePullPolicy: Always
              env:
                - name: SUBCOMMAND
                  value: "${SUBCOMMAND}"
                - name: DEBUG_LEVEL
                  value: ${{DEBUG_LEVEL}}
                - name: APP_SCRIPT
                  value: "app.sh"
                - name: THOTH_ENVIRONMENT
                  value: "${THOTH_ENVIRONMENT}"
                - name: PROMETHEUS_HOST_URL
                  valueFrom:
                    configMapKeyRef:
                      name: thoth
                      key: prometheus-host-url
                - name: KAFKA_BOOTSTRAP_SERVERS
                  valueFrom:
                    configMapKeyRef:
                      name: thoth
                      key: kafka-bootstrap-servers
                - name: KAFKA_CLIENT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: thoth
                      key: kafka-client-id
                - name: KAFKA_SSL_AUTH
                  valueFrom:
                    configMapKeyRef:
                      name: thoth
                      key: kafka-ssl-auth
                - name: KAFKA_RETENTION_TIME_SECONDS
                  valueFrom:
                    configMapKeyRef:
                      name: thoth
                      key: kafka-topic-retention-time
                - name: KAFKA_CAFILE
                  value: "/mnt/secrets/kafka_ca.crt"
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "500m"
                limits:
                  memory: "256Mi"
                  cpu: "500m"
              volumeMounts:
                - name: secrets
                  mountPath: /mnt/secrets
                  readOnly: true
          volumes:
            - name: secrets
              secret:
                secretName: "kafka-secret"
                items:
                  - key: kafka_ca.crt
                    path: kafka_ca.crt
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - advise-reporter-consumer
            from:
              kind: ImageStreamTag
              namespace: "${IMAGE_STREAM_NAMESPACE}"
              name: "advise-reporter:${IMAGE_STREAM_TAG}"
